### ISSUE TITLE
ffmpeg分割音頻的描述

### ISSUE THREAD

**Issue by dtlnor** [vcb-s/guides#1]
https://github.com/vcb-s/guides/tree/master/Basics/%5B03%5D%20%E7%A5%9E%E4%B8%80%E6%A0%B7%E7%9A%84%E5%B7%A5%E5%85%B7%E4%BB%AC#4-%E4%B8%80%E8%88%AC%E7%9A%84%E7%89%A9%E7%90%86%E5%88%87%E5%89%B2

> 音频的切割并不依赖于关键帧，我们可以使用 ffmpeg 对其进行精准到毫秒（实际是精确到 sample）的切割。

ffmpeg应该是精准到audio frame，对于wav这类格式来说1frame就是1个sample，但对于aac这类格式1frame有960/1024个sample。
参考
https://stackoverflow.com/questions/42144468/sample-accurate-audio-slicing-in-ffmpeg
(下面这个对frame的定义与上面的，以及media info的都不一样）
https://stackoverflow.com/questions/23216103/about-definition-for-terms-of-audio-codec

**Comment by sinsanction** [comment]
你误会了，这并不是说精准到单个sample，是说精确到sample（量级）。

我们在最后一句特别强调了aac的问题，就是因为aac只能按1024个sample为最小单位切割。（960的情况不清楚，大概是什么稀有类型）

**Comment by dtlnor** [comment]
原来如此，明白了。不过这句不仔细看的话比较容易产生歧义，可以考虑修饰一下。比如“实际上可以精确到 sample量级”或者是“无损格式可以精准到sample”，因为没了解过aac编码方式的话很容易进入“aac每个sample都可以独立无损切割出来”的误区。
