### ISSUE TITLE
内容更正：字体工具

### ISSUE THREAD

**Issue by ChuJiani** [vcb-s/guides#12]
## 更正内容

在 [基础部分 - 第十二章 - 添加字幕](https://guides.vcb-s.com/basic-guide-12#3-%E6%B7%BB%E5%8A%A0%E5%AD%97%E5%B9%95)，包含如下内容：

> 但是注意，`ListAssFonts` 不能检测出 `FontLoaderSub` 临时挂载的字体，会认为它们缺失。

经过实际验证，前者可以检测出后者临时加载的字体，但要求前者在启动时后者已经挂载完毕。

请针对此条目进行修改。

## 系统环境

- `Windows` 版本：`Windows 10 专业版 22H2 (19045.4046)`

- `ListAssFonts` 版本：`v190130`

- `FontLoaderSub` 版本：`r5`

两款软件均从 VCB-Studio 网站的 [“字体整合包”发布页](https://vcb-s.com/archives/1114) 下载。

## 补充

由于没有源码，对原因进行猜测：

`FontLoaderSub` 在运行时将字体临时加载到系统中。`ListAssFonts` 在每次启动时通过系统接口获取已安装（以及加载）的字体列表，并通过该列表对字体是否存在进行判断。在 `ListAssFonts` 运行过程中，该列表并不会刷新，因此如果在其启动后再使用 `FontLoaderSub` 加载或卸载字体，或直接在系统中安装、卸载字体，这些操作均不会被感知。

尤其是卸载操作，举个例子：加载字体 - 启动 `ListAssFonts` - 卸载字体。此时使用 `ListAssFonts` 仍能探测到刚刚加载的字体，会导致对当前字体加载情况做出错误判断，进而导致不必要的压制问题。

针对如上问题，重启 `ListAssFonts` 可以解决。

**Comment by sinsanction** [comment]
你使用的工具版本都太旧了（ListAssFonts 甚至都5年前的了），和现在的行为不一致。

ListAssFonts 早期可以识别临时挂载的字体，自 v190801 版本开始就只识别正常安装的字体，不再识别临时挂载的。

**Comment by ChuJiani** [comment]
收到:)
