### ISSUE TITLE
基础第一章别字更正

### ISSUE THREAD

**Issue by yotsubar** [vcb-s/guides#13]
- 171行：“YUV 也可以通过先行操作转换到 RGB”， 应为“YUV 也可以通过线性操作转换到 RGB”。
- 293行：“与逐行扫描相比，它的主要优点在于画面更为清晰、细节更加丰富。但由于数据量更大，传输效率相较逐行扫描要低一些”, 应该是“与隔行扫描相比，它的主要优点在于画面更为清晰、细节更加丰富。但由于数据量更大，传输效率相较隔行扫描要低一些”。

**Comment by sinsanction** [comment]
感谢报错，已修正
