### ISSUE TITLE
emm，一个无关紧要的建议

### ISSUE THREAD

**Issue by kskshaf** [vcb-s/guides#2]
vspipe 的参数 --y4m 已经可以换成 -c y4m 了吧，即使是使用 classic 也会出现这条消息：
`Deprecated option --y4m specified, use -c y4m instead`

![](https://i.slow.pics/WICbyRCf.png)
。。。。。。

**Comment by kskshaf** [comment]
没啥好说的

**Comment by AkarinVS** [comment]
https://github.com/AmusementClub/vapoursynth-classic/commit/f86d2be134c39288026f26b25ad62081ed378b7a

**Comment by sinsanction** [comment]
VS-C 无此问题，`--y4m` 和 `-c y4m` 均可使用，之后也无废弃 `--y4m` 的计划。

请注意，尽量规范标题和内容，以及之后任何原版 VS 的问题将不予受理。

**Comment by kskshaf** [comment]
> VS-C 无此问题，`--y4m` 和 `-c y4m` 均可使用，之后也无废弃 `--y4m` 的计划。
> 
> 请注意，尽量规范标题和内容，以及之后任何原版 VS 的问题将不予受理。

OK
