### ISSUE TITLE
res = res.text.ClipInfo() 报错

### ISSUE THREAD

**Issue by ShinodaCronus** [vcb-s/guides#4]
4. 视频属性和帧属性 
res = res.text.ClipInfo()，尝试了一下报错了
应该是res = core.text.ClipInfo()吧

**Comment by dtlnor** [comment]
@ShinodaCronus 
这里活用了滤镜串联
https://github.com/vcb-s/guides/tree/master/Basics/%5B05%5D%20VapourSynth%E5%9F%BA%E7%A1%80#2-%E5%8F%82%E6%95%B0%E4%BC%A0%E9%80%92
> 6. 滤镜串联
> VS 滤镜都是由 clip 作为第一个参数，在连续调用时可以串联，省去输入第一个参数。

这里假设了你前面已经存在了 res 这个 clip。你就可以通过
```py
res = res.text.ClipInfo() 
```
来调用 `text.ClipInfo()`。
而这一句等价于：
```py
res = core.text.ClipInfo(res) 
```

**Comment by ShinodaCronus** [comment]
懂了，感谢解释
